### ISSUE TITLE
连接在短时间内无输入时会自动断开连接（默认时间太短了）

### ISSUE THREAD

**Issue by zops** [KubeOperator/webkubectl#12]
通过Web界面已经连接上K8s，可是几秒中不输入就会断开连接。这个时间太短了，应该也就几秒钟。
是否可以让这个时间配置由用户自己来指定自动断开的时间呢？

**Comment by liqiang-fit2cloud** [comment]
我们这用的都挺好的，没有遇到你说的问题。
你是用了代理了么，nginx或者haproxy之类的？

**Comment by liqiang-fit2cloud** [comment]
我看了你的fork和commit，https://github.com/zops/webkubectl/commit/3edd3fb315b839b7e71179010416e3d52b541944
如果你要在k8s中部署webkubectl，那么你的ingress要支持websocket。
请参考：
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet
https://stackoverflow.com/questions/52883653/nginx-ingress-controller-websocket-support
https://blog.xujiuming.com/ming/9c16d977.html

**Comment by zops** [comment]
> 我[看了](https://github.com/zops/webkubectl/commit/3edd3fb315b839b7e71179010416e3d52b541944)你的fork和commit，[zops @ ](https://github.com/zops/webkubectl/commit/3edd3fb315b839b7e71179010416e3d52b541944)[3edd3fb](https://github.com/zops/webkubectl/commit/3edd3fb315b839b7e71179010416e3d52b541944)
> 如果你要在k8s中部署webkubectl，那么你的ingress要支持websocket。
> 请参考：
> [https](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet) : [//github.com/kubernetes/ingress-nginx/blob/master/ docs / user-guide / nginx-configuration / annotations.md＃configuration-snippet ](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet)
> [https://stackoverflow.com/questions/52883653/nginx-ingress-controller-websocket-support ](https://stackoverflow.com/questions/52883653/nginx-ingress-controller-websocket-support)
> [https://blog.xujiuming.com/ming/ 9c16d977.html](https://blog.xujiuming.com/ming/9c16d977.html)


谢谢您的帮助。
目前ingress支持websocket，经过您给的提示，排查了ingress前端代理（nginx tcp代理），导致自动断开的原因是proxy_timeout参数导致。将该时间增大解决问题。

nginx-tcp-proxy：80
              |
一一一一一一一一一
|                              |
ingress                 ingress
