### ISSUE TITLE
使用api获取的token打开url 报错 base64: invalid input

### ISSUE THREAD

**Issue by YangDevops** [KubeOperator/webkubectl#16]
Welcome to Web Kubectl, try kubectl --help.
base64: invalid input

**Comment by liqiang-fit2cloud** [comment]
调用的哪个API获取的token，如果是https://github.com/KubeOperator/webkubectl#get-token-by-kubeconfig-file 的话，kubeconfig文件的内容要base64一下。
![image](https://user-images.githubusercontent.com/20766823/106586635-ad724380-6583-11eb-9f60-e0884bc68073.png)

**Comment by YangDevops** [comment]
可以了,我BASE64那块写的有问题。
感谢哈
