### ISSUE TITLE
如果能开放个API 读取命令行操作记录 结合asciinema用于回放、审计webkubectl的操作就更完美啦

### ISSUE THREAD

**Issue by YangDevops** [KubeOperator/webkubectl#17]

**Comment by liqiang-fit2cloud** [comment]
Hi,
我司的另一款开源堡垒机产品JumpserServer不仅包含了webkubectl的功能，也包含了你说的回放、审计等功能。
相信JumpServer就是你想要的。
https://www.jumpserver.org/
https://docs.jumpserver.org/zh/master/user-guide/apps/user-kubernetes/

**Comment by liqiang-fit2cloud** [comment]
我们要关闭这个issue，如果有其他需要可以重新打开或者提交新的issue。
感谢您的建议。
