### ISSUE TITLE
Is there any authentication for the UI ? 

### ISSUE THREAD

**Issue by saiyam1814** [KubeOperator/webkubectl#19]
It would be good if there is any authentication for login into the UI

**Comment by liqiang-fit2cloud** [comment]
Yes, you can set env GOTTY_CREDENTIAL=user:pwd to enable the basic authentication.
`docker run --name="webkubectl" -p 8080:8080 -e GOTTY_CREDENTIAL=user01:password01 -d --privileged kubeoperator/webkubectl`

**Comment by saiyam1814** [comment]
Awesome thanks, So I am writing a  blog (almost finished) where I show how to deploy and use webkubectl inside Kubernetes cluster

**Comment by liqiang-fit2cloud** [comment]
Good to know that, thank you. :smiley:

**Comment by jainpratik163** [comment]
is there any way where we can define multiple usernames and passwords for diff people as I can see with basic authentication we can only provide one username and password?

**Comment by liqiang-fit2cloud** [comment]
Not support this.

**Comment by jainpratik163** [comment]
any plan for this support?

**Comment by liqiang-fit2cloud** [comment]
> any plan for this support?

Would you please log a new issue for this feature?

**Comment by liqiang-fit2cloud** [comment]
> is there any way where we can define multiple usernames and passwords for diff people as I can see with basic authentication we can only provide one username and password?

Multiple username and password is supported since [v2.11.0](https://github.com/KubeOperator/webkubectl/releases/tag/v2.11.0)
