### ISSUE TITLE
GUI customization

### ISSUE THREAD

**Issue by sreejithwpg** [KubeOperator/webkubectl#22]
Hi,

Is it possible to customize the web GUI like setting custom icon, background..etc? Is there any way to store the kubeconfig or token details in the app instead of the web browser?

**Comment by liqiang-fit2cloud** [comment]
Hi,
The web GUI is just for a quick start.
Actually another best practice of webkubectl is integration with your own application, your application has its own web UI and manage cluster informations including kubeconfig or bearer tokens, call the api of webkubectl when need to connect cluster via kubectl in web terminal.

**Comment by liqiang-fit2cloud** [comment]
Hi,
We are going to close this issue, if you have any problem you can reopen it or log a new one.
