### ISSUE TITLE
K8s中部署报错

### ISSUE THREAD

**Issue by gorexlv** [KubeOperator/webkubectl#24]
在k8s中部署，进去终端的时候报错: 
unshare: unshare(0x20020000): Operation not permitted

请问在k8s中部署，需要做什么配置吗？

**Comment by gorexlv** [comment]
应该是特权模式的问题。

请问webkubectl可以提供在非特权模式下的终端功能吗？

**Comment by liqiang-fit2cloud** [comment]
感谢关注。
现在会话隔离是用Linux的Namespace实现的，每个会话是一个临时Namespace，创建Namespace需要特权。
所以没有特权的话就做不到会话隔离，目前还没想到其他方案能实现隔离。
