### ISSUE TITLE
how to use this with OpenShift

### ISSUE THREAD

**Issue by jainpratik163** [KubeOperator/webkubectl#26]
we have many openshift clusters and we want to give this tool to people who wish to run some kubectl command from the backend how we can do this.
we don't want to create a config file for all users.
and how we can also implement security.

**Comment by liqiang-fit2cloud** [comment]
Hi Jain,

> we have many openshift clusters and we want to give this tool to people who wish to run some kubectl command from the backend how we can do this

I think this is the best choice for you, see [advantages](https://github.com/KubeOperator/webkubectl#advantage)
You can do it like this.
![image](https://user-images.githubusercontent.com/20766823/185523965-4c94a0f0-7938-4a39-9588-7ac76f3915ee.png)

> we don't want to create a config file for all users.

Not sure what you mean. 
Every user can manage his own config files in this tool and they are invisible to each others. But if you wish users to have different privileges, you have to create different ServiceAccount.

> how we can also implement security.

Security is fully considered in webkubectl,  like session isolation and [basic authentication](https://github.com/KubeOperator/webkubectl/issues/19)

**Comment by jainpratik163** [comment]
thanks, @liqiang-fit2cloud for the reply.
in Openshift we use to get out own API tokens and with that token, we can also login from the backend, so in the same way, we can also login into this webkubectl ?

oc login --token=<token> --server=<openshiftURL>

**Comment by liqiang-fit2cloud** [comment]
Never tried but I think the token and server of oc is valid to webkubectl.
![image](https://user-images.githubusercontent.com/20766823/185577921-36cd65b0-3b00-44a0-bea1-39268f8760da.png)
But kubectl is only used with standard Kubernetes API and resources in OpenShift.
See https://docs.openshift.com/container-platform/3.11/cli_reference/differences_oc_kubectl.html

**Comment by jainpratik163** [comment]
ok, I will try.

**Comment by jainpratik163** [comment]
thanks, it is working fine with the token.
and if we want to add oc client into the docker image we can add it?

**Comment by liqiang-fit2cloud** [comment]
you can try, I suppose it works fine.

**Comment by jainpratik163** [comment]
i tried to create new docker images with oc client add but getting the below error
anything extra we also need to do ?

bash-5.1# which oc
/usr/bin/oc
bash-5.1# ls -lrt /usr/bin/oc
-rwxrwxrwx    1 root     root      72461736 Aug 23 05:05 /usr/bin/oc
bash-5.1# oc
bash: /usr/bin/oc: No such file or directory
bash-5.1#

**Comment by liqiang-fit2cloud** [comment]
Seems oc cli requires glibc, you have to change base image.
 https://github.com/openshift/origin/issues/11135

**Comment by jainpratik163** [comment]
i will try this but can we also include this oc client in same docker Image?

**Comment by liqiang-fit2cloud** [comment]
Sorry we have no plan to support oc cli.
