### ISSUE TITLE
Question: how can i change the asset.go when i change the static contents

### ISSUE THREAD

**Issue by jinyoung** [KubeOperator/webkubectl#6]
Firstly congratulations for your fantastic project!

Now I'm trying to hack your project to integrate with my small open source project.
So I have made some changes in the front-end side, and I simply built the project with the Dockerfile, and there are some makefile that looks doing some npm build, However the changes are not applied at all.

It looks the changes in front-ends must be reflected to the "asset.go" file, specifically to the _staticJsGottyBundleJs variable. And your team changed the modified date and the contents length corresponding to the changes as well. I think it looks done by some build tools something. 

How did you do this? 

Thank you.

**Comment by jinyoung** [comment]
I found that the file generated by the go-bindata tool.

Thank you.

**Comment by liqiang-fit2cloud** [comment]
👍🏻
